version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - npm install -g @angular/cli@6.0.0
  build:
    commands:
      
      # run the build
      - ng build
artifacts:
  files:
    # bundle everything as a build artifact, except hidden files
    - '**/*'
